[irc]
    [irc.local]
    Server="inspircd:6667"
    Nick="Matterbridge"
    # ColorNicks=true

[discord]
    [discord.testing]
    Token="<token>"
    Server="Testing"
    ShowEmbeds=true

[slack]
    [slack.test]
    Token="<token>"
    PrefixMessagesWithNick=true

[general]
    ShowJoinPart=true
    RemoteNickFormat="[{PROTOCOL}/{CHANNEL}] <{NICK}> "

[[gateway]]
    name="comms-gateway"
    enable=true

    [[gateway.inout]]
        account="irc.local"
        channel="#Local"

    [[gateway.inout]]
        account="discord.testing"
        channel="general"

    # [[gateway.inout]]
    # account="slack.test"
    # channel="testing"
